Traceback (most recent call last):
  File "experiments/sample_tracking.py", line 11, in <module>
    wandb.log({"loss": loss})
NameError: name 'loss' is not defined